version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: pioneer_pixel_postgres
    environment:
      POSTGRES_DB: pioneer_pixel_db
      POSTGRES_USER: pioneer_user
      POSTGRES_PASSWORD: pioneer_pass
    ports:
      - "5432:5432"
    volumes:
      - pioneer_pixel_pgdata:/var/lib/postgresql/data

volumes:
  pioneer_pixel_pgdata:
