spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pioneer_pixel_db
    username: pioneer_user
    password: pioneer_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    clean-disabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    org.flywaydb: DEBUG
