spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pioneer_pixel_db
    username: pioneer_user
    password: pioneer_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true