spring:
  main:
    allow-bean-definition-overriding: true

  task:
    scheduling:
      pool:
        size: 5

  datasource:
    url: jdbc:postgresql://localhost:5432/pioneer_pixel_db
    username: pioneer_user
    password: pioneer_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    clean-disabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration

  elasticsearch:
    uris: http://localhost:9200/

logging:
  level:
    org.flywaydb: DEBUG

search:
  type: jpa  # или elastic для поиска через Elasticsearch
